name: MLOps Gatekeeper Pipeline

on:
  push:
    branches:
      - "**"

jobs:


  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Run linter
        run: echo "linter running"


  train:
    needs: linter
    runs-on: ubuntu-latest


    if: >
      needs.linter.result == 'success' &&
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, '[run-train]')

    steps:


      - name: Run training
        run: |
          echo "training model..."
          echo "model output" > model.txt


      - name: Handle failure
        if: failure()
        run: |
          echo "Error happened during training" > error_logs.txt


      - name: Upload error logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error_logs.txt


      - name: Upload model artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.txt

      - name: Cleanup
        if: always()
        run: echo "Cleaning up temporary files..."
