name: MLOps Gatekeeper Pipeline

on:
  push:
    branches:
      - "**"

jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: run linter
        run: echo "linter running"

  train:
    needs: linter
    runs-on: ubuntu-latest

    if: >
      needs.linter.result == 'success' &&
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, '[run-train]')

    steps:
      - name: run training
        run: echo "train running"

      - name: handle failure
        if: failure()
        run: echo "Error logs" > error_logs.txt

      - name: upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error_logs.txt

      - name: cleanup logs
        if: always()
        run: echo "Cleaning up temporary cloud volumes..."
