name: MLOps Gatekeeper Pipeline

on:
  push:
    branches:
      - "**"

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install linter
        run: pip install flake8

      - name: run linter
        run: flake8 . 


  train:
    needs: lint
    runs-on: ubuntu-latest

    if: >
      needs.lint.result == 'success' &&
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, '[run-train]')

    steps:
      - uses: actions/checkout@v4

      - name: run training
        run: |
          python train.py || exit 1

      - name: save logs
        if: failure()
        run: echo "training failed" > error_logs.txt

      - name: upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error_logs.txt

      - name: cleanup
        if: always()
        run: echo "Cleaning up temporary cloud volumes..."
